# Generated by Django 5.0.4 on 2024-04-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rashmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeenName', models.CharField(max_length=255)),
                ('employeeAge', models.CharField(max_length=255)),
                ('employeeId', models.CharField(max_length=255)),
            ],
        ),
    ]
