# Generated by Django 5.0.4 on 2024-04-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rashmi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rashmi',
            old_name='employeenName',
            new_name='employeeName',
        ),
    ]
