# Generated by Django 5.0.4 on 2024-04-18 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rashmi', '0002_rename_employeenname_rashmi_employeename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rashmi',
            old_name='employeeAge',
            new_name='employeeage',
        ),
        migrations.RenameField(
            model_name='rashmi',
            old_name='employeeId',
            new_name='employeeid',
        ),
        migrations.RenameField(
            model_name='rashmi',
            old_name='employeeName',
            new_name='employeename',
        ),
    ]
